version: '3.3'

services:
  client_diarization:
    build:
      context: .
      dockerfile: Dockerfile
    image: elmira96/gpt-speaker-diarization:v0.1.0
    hostname: client_diarization
    container_name: client_diarization
    restart: always
    environment:
      - OPENAI_API_KEY=sk-***
      - NUM_WORKERS=4
    volumes:
      - ./resources:/resources:rw
    ports:
        - 8012:8000
